version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mutual-fund-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mutualfunds
    volumes:
      - mongodb_data:/data/db
    networks:
      - mutual-fund-network

  backend:
    build: ./server
    container_name: mutual-fund-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/mutualfunds?authSource=admin
      - JWT_SECRET=your_super_secret_jwt_key_here
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - mutual-fund-network

  frontend:
    build: ./client
    container_name: mutual-fund-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mutual-fund-network

volumes:
  mongodb_data:

networks:
  mutual-fund-network:
    driver: bridge
